package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorApp.idl
* Monday, 29 May, 2023 4:48:34 AM IST
*/

public interface CalculatorOperations 
{
  float add (float x, float y);
  float subtract (float x, float y);
  float multiply (float x, float y);
  float divide (float x, float y);
} // interface CalculatorOperations
